{"uuid": "1923526b-c9b1-4f7c-a263-8c6f1c6888b9", "children": ["5262710e-0fb8-40bb-a8be-a310dff3da35", "b8d38d83-4f5b-4034-8ea5-cada4c1bdf58", "dd12da67-c7bf-432f-addc-9462c58d7565", "8e73dc5b-e6ea-4381-ad96-fc16d1aa31fa", "70e29edf-507e-4723-b60d-46f47a5122ea", "063a5008-8414-4d7a-872d-096c03f28278"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ifname'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 403, in get_interface_details\n    wifi_info[j[\"ifname\"]] = [j[\"config\"][\"ssid\"], j[\"config\"][\"encryption\"], \"\"]\n"}, "attachments": [{"name": "ucentral_config: ", "source": "3e607db3-03d4-4a34-bebc-38a95db9c48e-attachment.attach"}, {"name": "Time Took to apply Config: 236.61778855323792", "source": "80b3dff3-d475-4951-91a8-aeae52e79068-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "5f7bf5df-2da9-4e7f-ae5a-830322e7b395-attachment.attach"}, {"name": "AP LOgs: ", "source": "7ce89f32-3902-419a-bb80-7127db209773-attachment.attach"}], "start": 1628904398595, "stop": 1628904682090}], "start": 1628904398592, "stop": 1628904682492}