{"uuid": "258d72f2-9881-4508-aa23-df7a0ba344b2", "children": ["fdea24d9-a98d-4e75-af46-b02023833809", "6acd672d-bfea-44d2-af25-a2f6412ed7fd", "6bf8e30e-4244-4925-a289-1aac3c376ebf", "be19c341-80b2-43ca-8aad-2c8bd5e8cff6", "65e2dcb0-51e5-43db-a9bc-a9dee4163537", "21c4b615-fc93-4aad-93d4-85662501bb6c"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ifname'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 403, in get_interface_details\n    wifi_info[j[\"ifname\"]] = [j[\"config\"][\"ssid\"], j[\"config\"][\"encryption\"], \"\"]\n"}, "attachments": [{"name": "ucentral_config: ", "source": "f4bfcfe5-eafb-425c-9f94-2f5b30c8839a-attachment.attach"}, {"name": "Time Took to apply Config: 33.87177348136902", "source": "780f9200-23cd-430e-88a5-bd3fd2bbb884-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "3dd13715-4f6a-456f-bfce-bc5bf37cc3e4-attachment.attach"}, {"name": "AP LOgs: ", "source": "04e4a8d4-5e1d-4911-994e-7d464cac5ef2-attachment.attach"}], "start": 1629159980678, "stop": 1629160046043}], "start": 1629159980678, "stop": 1629160046432}