{"uuid": "64caf109-f962-4d1e-add9-d54fe82fef0b", "children": ["10b2d0d3-928c-4635-8e48-e9e1e66b521b", "e9b880a2-c154-4e7c-a3e8-b627c39dad74", "fc8a17a1-5b71-4094-b08d-a38fb31e99c0", "a927e0dd-0502-405f-a7f8-a7001089833b", "fc783a90-63b6-4fec-8aae-bcc95105e698", "a4aec14b-41ee-4a60-a078-d2af641997d2"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ifname'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 401, in get_interface_details\n    wifi_info[j[\"ifname\"]] = [j[\"config\"][\"ssid\"], j[\"config\"][\"encryption\"], j[\"config\"][\"key\"]]\n"}, "attachments": [{"name": "ucentral_config: ", "source": "2f879d5f-c350-4600-ad14-5f492c77cfd4-attachment.attach"}, {"name": "Time Took to apply Config: 55.639477491378784", "source": "ed51c0b7-6d59-4bbd-b5e5-941b4beea9a4-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "3c9ee398-ef58-43f1-8a67-0aaa396d05a5-attachment.attach"}, {"name": "AP LOgs: ", "source": "f58abce5-4133-44cd-bd0e-7fccddb67116-attachment.attach"}], "start": 1629160252578, "stop": 1629160336790}], "start": 1629160252578, "stop": 1629160337172}