{"uuid": "849c271c-ece3-4d7d-af42-bdd819c3ffc7", "children": ["95a39f5f-8f5b-4012-860f-43e8d5c22061", "3a8b32f2-de94-4e5b-b818-7fce8bfb00e4", "64096e92-ea11-4b44-b394-749bc765c4e5", "deec5c3b-1528-4cb8-8332-f812d251775b", "8011631b-8667-4d5c-b785-a1b19cc7e6d0", "24058c6c-0cc6-4d98-b537-ab3114f78e09"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "KeyError: 'ifname'\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/basic/conftest.py\", line 79, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_id,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 292, in setup_profiles\n    ap_wifi_data = ap_ssh.get_interface_details()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 403, in get_interface_details\n    wifi_info[j[\"ifname\"]] = [j[\"config\"][\"ssid\"], j[\"config\"][\"encryption\"], \"\"]\n"}, "attachments": [{"name": "ucentral_config: ", "source": "8177eae1-1857-42a7-a3f6-91963c7f1d19-attachment.attach"}, {"name": "Time Took to apply Config: 57.86462950706482", "source": "5970db41-90f1-418d-87ef-5f39c552cc0e-attachment.attach"}, {"name": "Success : Active Config in AP: ", "source": "dd95e983-aa71-4dd8-b1dd-2eb3d3cbb608-attachment.attach"}, {"name": "AP LOgs: ", "source": "2ca41a72-b217-4def-b7bc-00be54b0b9a6-attachment.attach"}], "start": 1629160327677, "stop": 1629160420840}], "start": 1629160327677, "stop": 1629160421291}